name: Deploy para VPS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4

      - name: Verificar estado do repositório
        run: |
          git status
          git log -1

      - name: Verificar configuração do Git
        run: |
          git config --list

      - name: Verificar permissões do diretório
        run: |
          ls -la

      - name: Instalar dependencias
        run: npm install

      - name: Build do projeto
        run: npm run build
      - name: Deploy para meu hosting VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "DECISAO/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_TARGET: ${{ secrets.REMOTE_TARGET }}

        
