name: "Deploy para VPS"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
  runs-on: ubuntu-latest
  steps:
    - name: "Baixar o código"
    - uses: actions/checkout@v4
    

    - name: "Copiar arquivo para vps"
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        host: "185.173.110.103"
        username: "root"
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: /var/www/html